<?php

/**
 * @file
 * Main file for the GDPR Notice.
 */

// settings vars to make available as js

function gdpr_notice_preprocess_html(&$variables) {

  $main_message = variable_get('gdpr_notice_message', 'This website uses cookies to provide you with an improved user experience. By continuing to browse this site, you consent to the use of cookies and similar technologies.');
  $main_link_text = variable_get('gdpr_notice_link_text', 'privacy policy');
  $main_link = variable_get('gdpr_notice_link', '/about/privacy-policy');
  $main_button_text = variable_get('gdpr_notice_button_text', 'OK');  

  drupal_add_js(array('gdpr_notice' => array('gdpr_message' => $main_message)), array('type' => 'setting'));
  drupal_add_js(array('gdpr_notice' => array('gdpr_link' => $main_link)), array('type' => 'setting'));
  drupal_add_js(array('gdpr_notice' => array('gdpr_link_text' => $main_link_text)), array('type' => 'setting'));
    drupal_add_js(array('gdpr_notice' => array('gdpr_button_text' => $main_button_text)), array('type' => 'setting'));
}

/**
 * Implements hook_menu().
 */

function gdpr_notice_menu() {

  $items = array();

  $items['admin/config/user-interface/gdpr_notice'] = array(
    'title' => 'GDPR Notice',
    'description' => 'Configuration for GDPR notice',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gdpr_notice_settings'),
    'access arguments' => array('administer site configuration'),
  );

  return $items;
}

/**
 * Function gdpr_notice_settings.
 */

function gdpr_notice_settings($form, &$form_state) {

  $form['gdpr_notice_message'] = array(
    '#title' => t('Text to appear in the GDPR notice:'),
    '#type' => 'textfield',
    '#description' => t('A brief sentence notifying site visitors that your site sets cookies'),
    '#default_value' => variable_get('gdpr_notice_message', ''),
    '#size' => 130,
    '#maxlength' => 260,
    '#resizable' => FALSE,
  );

  $form['gdpr_notice_link'] = array(
    '#title' => t('Link to the site privacy page:'),
    '#type' => 'textfield',
    '#description' => t('The path to the site\'s privacy page. Use a starting slash, e.g. "/about/privacy-policy". You can use a full path if pointing to another site.'),
    '#default_value' => variable_get('gdpr_notice_link', '/about/privacy-policy'),
    '#size' => 80,
    '#maxlength' => 130,
    '#resizable' => FALSE,
  );

  $form['gdpr_notice_link_text'] = array(
    '#title' => t('Text for the link to the site privacy page:'),
    '#type' => 'textfield',
    '#description' => t('This is the text that will appear for the link to the privacy policy'),
    '#default_value' => variable_get('gdpr_notice_link_text', 'privacy policy'),
    '#size' => 30,
    '#maxlength' => 60,
    '#resizable' => FALSE,
  );

  $form['gdpr_notice_button_text'] = array(
    '#title' => t('Text for the acceptance button:'),
    '#type' => 'textfield',
    '#description' => t('This is the text that will appear on the button to accept'),
    '#default_value' => variable_get('gdpr_notice_button_text', 'OK'),
    '#size' => 10,
    '#maxlength' => 20,
    '#resizable' => FALSE,
  );

  return system_settings_form($form);
}
