<?php

/**
 * @file
 * Main file for the GDPR Notice.
 */

// settings vars to make available as js

function gdpr_notice_preprocess_html(&$variables) {

  $main_message = variable_get('gdpr_notice_message', '(go to /admin/config/user-interface/gdpr_notice to set this text)');
  $main_link = variable_get('gdpr_notice_link', '/about/privacy-policy');

  drupal_add_js(array('gdpr_notice' => array('gdpr_message' => $main_message)), array('type' => 'setting'));
  drupal_add_js(array('gdpr_notice' => array('gdpr_link' => $main_link)), array('type' => 'setting'));
}

/**
 * Implements hook_menu().
 */

function gdpr_notice_menu() {

  $items = array();

  $items['admin/config/user-interface/gdpr_notice'] = array(
    'title' => 'GDPR Notice',
    'description' => 'Configuration for GDPR notice',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gdpr_notice_settings'),
    'access arguments' => array('administer site configuration'),
  );

  return $items;
}

/**
 * Function gdpr_notice_settings.
 */

function gdpr_notice_settings($form, &$form_state) {

  $form['gdpr_notice_message'] = array(
    '#title' => t('Text to appear in the GDPR notice:'),
    '#type' => 'textfield',
    '#description' => t('A brief sentence notifying site visitors that your site sets cookies'),
    '#default_value' => variable_get('gdpr_notice_message', ''),
    '#size' => 130,
    '#maxlength' => 260,
    '#resizable' => FALSE,
  );

  $form['gdpr_notice_link'] = array(
    '#title' => t('Link to the site privacy page:'),
    '#type' => 'textfield',
    '#description' => t('The path to the site\'s privacy page. Use a starting slash, e.g. "/about/privacy-policy". You can use a full path if pointing to another site.'),
    '#default_value' => variable_get('gdpr_notice_link', '/about/privacy-policy'),
    '#size' => 80,
    '#maxlength' => 130,
    '#resizable' => FALSE,
  );

  return system_settings_form($form);
}
